version: '3.1'

services:
    mysql:
        image: mysql:5.7
        container_name: spring_mysql
        volumes:
              - spring_mysql_volume:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: spring
            MYSQL_USER: spring
            MYSQL_PASSWORD: password
        ports:
            - 3309:3306
        networks:
            - spring_net
volumes:
    spring_mysql_volume: {}
networks:
    spring_net: {}
